### ISSUE TITLE
Doesn't build (Raspberry Pi 2)

### ISSUE THREAD

**Issue by funkyguy4000** [TeraHz/PCA9685#1]
Just cloned this repo and it doesn't build.  I noticed that it was trying to include your "I2C.h" file in the PCA9685.h file so I cloned that and tried two things:
1) Move the I2C source and header to the PCA9685 source folder and attempted to build which didn't work.
2) Build just the I2C project which gave the error:

```
pi@raspberrypi2:~/MasterControl/PiLight/I2C/src$ make
g++ -O3 -fPIC -g -Wall -Werror      -c -o I2C.o I2C.cpp
In file included from I2C.cpp:30:0:
/usr/include/linux/i2c-dev.h:37:8: error: redefinition of âstruct i2c_msgâ
In file included from I2C.cpp:29:0:
/usr/include/linux/i2c.h:67:8: error: previous definition of âstruct i2c_msgâ
In file included from I2C.cpp:30:0:
/usr/include/linux/i2c-dev.h:89:7: error: redefinition of âunion i2c_smbus_dataâ
In file included from I2C.cpp:29:0:
/usr/include/linux/i2c.h:125:7: error: previous definition of âunion i2c_smbus_dataâ
<builtin>: recipe for target 'I2C.o' failed
make: *** [I2C.o] Error 1
```

How was this meant to be used seeing as how nothing compiles?

**Comment by funkyguy4000** [comment]
Figured it out I believe, I haven't tested the actual functionality yet but both of the repos compile down into their .so library.  Since I'm on the Raspberry Pi 2, and <linux/i2c.h> isn't used here, I commented that include out and left the <linux/i2c-dev.h> since I know that one is used.  Once I built it, they created their libraries.  I'll let you know if there are any further problems and if not, I'll close the issue.  

It would be nice if you could figure out some way of handling this on the RPi but you dont need to so long as this issue is documented.

**Comment by funkyguy4000** [comment]
Alright so I'm still having issues.  Basically whats happening is the actual output isn't changing.  
It is all illustrated here: http://raspberrypi.stackexchange.com/questions/32202/writing-to-i2c-device-file-using-c

Could you provide a little better documentation on the methods for this library?  Quite frankly I'm not sure if the setPWM method requires a value between 0-255 or 0-4096 or what.

**Comment by funkyguy4000** [comment]
I had a hardware issue and then somehow missed the comments in the file.  I figured everything out, thanks for the awesome libraries!

**Comment by TeraHz** [comment]
You are correct, the repo needs a readme. 

From your stackexchange question, it appears that you're using the library properly. If you see the syslog messages, then data was sent on the I2C bus. If you have a scope or logic analyzer, you can check either the PWM pins on the chip or the i2c bus to see if bits are actually changing.

Since this is a 12bit chip, it has 4096 steps. The values setPWM takes are 0-4095.

**Comment by TeraHz** [comment]
Nice, glad things worked out. Feel free to contribute a readme to help the next person :)

**Comment by funkyguy4000** [comment]
Sure! I'll look after the I2C and PCA9685 repos and help out if possible.
