### ISSUE TITLE
bug in register addresses for write

### ISSUE THREAD

**Issue by NaumionokAndrei** [TeraHz/PCA9685#2]
file PCA9685: func: void PCA9685::setPWM(uint8_t led, int on_value, int off_value) {
        i2c->write_byte(LED0_ON_L + LED_MULTIPLYER \* (led - 1), on_value & 0xFF);
        i2c->write_byte(LED0_ON_H + LED_MULTIPLYER \* (led - 1), on_value >> 8);
        i2c->write_byte(LED0_OFF_L + LED_MULTIPLYER \* (led - 1), off_value & 0xFF);
        i2c->write_byte(LED0_OFF_H + LED_MULTIPLYER \* (led - 1), off_value >> 8);
}
if (led==0) address = LED0_ON_L - LED_MULTIPLYER
 its not led0 address

**Comment by TeraHz** [comment]
Hi there,

This was written so that you can pass the led channel number (1-16) when setting the PWN. Indeed 0 would result in a bad address. I can put a check in there and make it clear in the docs.

Thanks for reporting.
