### ISSUE TITLE
Doesn't build on raspberry pi

### ISSUE THREAD

**Issue by tommaso1** [TeraHz/PCA9685#3]
It cannot find I2C.h when making, is there any way to build it? Cannot build neither, I2C on the other repo..

**Comment by TeraHz** [comment]
Hi @tommaso1,

I haven't tried building on a rpi. Try this:

- Clone the [I2C](https://github.com/TeraHz/I2C) repo.
- Edit `src/Makefile`'s _CXX_ entry to reflect your g++ compiler
- Run `make` in the src dir of it
- Clone the [PCA9685](https://github.com/TeraHz/PCA9685) repo in the same parent dir as the I2C one
- Edit `src/Makefile`'s _CXX_ entry to reflect your g++ compiler
- Run `make` in the src dir

If that doesn't work, post what error you get and I'll try to help.

**Comment by TeraHz** [comment]
@tommaso1 I just tried it on a RPi 3/Raspbian. The above steps work on Raspbian Stretch after setting _CXX_ to `g++` - use the commented out entry. 
Hope this helps.

**Comment by tommaso1** [comment]
Thanks!

**Comment by Marko882** [comment]
When i run make I2C src dir i get this error -> 

I2C.cpp: In member function ‘void I2C::openfd()’:
I2C.cpp:105:16: error: ‘I2C_SLAVE’ was not declared in this scope
  if (ioctl(fd, I2C_SLAVE, _i2caddr) < 0) {

If u got any idea what could this be !?
